# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlantCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlantCare
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'ProgressHUD'
  pod 'KILabel', '1.0.0'
end
